### ISSUE TITLE
Option for explicit start and explicit end

### ISSUE THREAD

**Issue by Andrew-Sheridan** [jumanjihouse/pre-commit-hook-yamlfmt#18]
Hi there! really appreciate this package and its authors :)

I'm curious if it would be possible to add an option for explicit start and explicit end?

Here explicit start is currently hardcoded: 
- https://github.com/jumanjihouse/pre-commit-hook-yamlfmt/blob/master/pre_commit_hooks/yamlfmt#L88

Thanks for your time

**Comment by dudicoco** [comment]
I've added support to remove explicit start, released in 0.1.0.

```
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.1.0
  hooks:
  - id: yamlfmt
    args:
    - --implicit_start
```

**Comment by archoversight** [comment]
Would there be any appetite to adding an explicit end?

**Comment by archoversight** [comment]
@Andrew-Sheridan take a look at my PR: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt/pull/21 

You may use this right now with:

```
- repo: https://github.com/archoversight/pre-commit-hook-yamlfmt.git
  rev: 0.1.0-explicit
  hooks:
  - id: yamlfmt
    args: [--explicit_end, --explicit_start]
```
