### ISSUE TITLE
Unexpected ':'

### ISSUE THREAD

**Issue by tdegeus** [jumanjihouse/pre-commit-hook-yamlfmt#27]
I have the following bit in `.pre-commit-config.yaml`
```yaml
---
repos:
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.0.11
      hooks:
          - id: yamlfmt
    - repo: https://github.com/PyCQA/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            args: [--max-line-length=100, --per-file-ignores=python/myrepo/*.py:F401]
```
However, I'm getting a persistent 
```
while scanning a plain scalar
  in ".pre-commit-config.yaml", line 11, column 43
found unexpected ':'
  in ".pre-commit-config.yaml", line 11, column 81
```

The syntax that I use in legal, and I think the only syntax. How do I get rid of this error?
