### ISSUE TITLE
Is it possible to ignore a line ?

### ISSUE THREAD

**Issue by nitrogene** [jumanjihouse/pre-commit-hook-yamlfmt#45]
Hello,

I am working on a docker compose including mongo (among other services), and I have an issue with yamlfmt. Let's look at the following example:

```yaml
  mongo:
    image: $MONGO_IMAGE:$MONGO_VERSION
    container_name: mongo
    hostname: mongo
    volumes:
      # Persistent docker volume
      - mongo-storage:/data/db:rw
    networks:
      - logging_network
    restart: 'no'
```
Yamlfmt turns it into:

```yaml
  mongo:
    image: $MONGO_IMAGE:$MONGO_VERSION
    container_name: mongo
    hostname: mongo
    volumes:
      # Persistent docker volume
      - mongo-storage:/data/db:rw
    networks:
      - logging_network
    restart: no
```

Please notice that the single quotes around no are removed. But they are required. Is it possible to make yamlfmt ignore this line ?
