### ISSUE TITLE
Recommended autoformatter introduces lint errors

### ISSUE THREAD

**Issue by ggoretkin-bdai** [jumanjihouse/pre-commit-hook-yamlfmt#48]
For YAML files like this:

```yaml
location: external
sources:
  - repo: foo
    name: bar
    rev: main
    type: git
    params:
    sparse_paths:
      -
    links:
      -
```

The autoformatter adds trailing spaces:

```diff
diff --git a/test.yaml b/test.yaml
index 272e7eb..f1b8fbe 100644
--- a/test.yaml
+++ b/test.yaml
@@ -1,12 +1,13 @@
+---
 location: external
 sources:
-  - repo: foo
-    name: bar
-    rev: main
-    type: git
-    params:
-    sparse_paths:
-      -
-    links:
-      -
+    - repo: foo
+      name: bar
+      rev: main
+      type: git
+      params:
+      sparse_paths:
+          - 
+      links:
+          - 
```

![image](https://user-images.githubusercontent.com/124000349/235828604-9bb8c11a-7e76-4a59-a0cb-e793516e959d.png)
