### ISSUE TITLE
empty list item gets trailing whitespace added

### ISSUE THREAD

**Issue by commonism** [jumanjihouse/pre-commit-hook-yamlfmt#56]
The following example is 
```yaml
a:
  -
```

hard to get right with 

```yaml
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-d", "{extends: relaxed, rules: {empty-lines: disable, line-length: {max: 1500}}}", --strict, --format, parsable]

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --preserve-quotes, --implicit_start, --width, '1500']
```

yamlfmt wants to add a trailing whitespace, the others disagree.
Only option so far is manually exclude file from yamlfmt.

**Comment by alexdewar** [comment]
I'm having the same issue. It's a shame -- I'd like to use this hook, but I don't want to disable the `trailing-whitespace` hook either.

**Comment by commonism** [comment]
exclude:

```yaml

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --preserve-quotes, --implicit_start, --width, '1500']
        exclude: tests/fixtures/schema-enum.yaml

```
